name: WorkFlow
on:
  push:
    branches:
      - feature-esteban-espinoza

jobs:
    SAST:
      runs-on: ubuntu-latest
      steps: 

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Clonar Repo
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
          args: >
            -Dsonar.organization=altheus26 \
            -Dsonar.projectKey=altheus26_Laboratorio-final \
            
        
