name: WorkFlow
on:
  push:
    branches:
      - feature-esteban-espinoza

jobs:
    SAST:
      runs-on: ubuntu-latest
      steps: 

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Clonar Repo
        uses: actions/checkout@v4

    #  - name: SonarCloud Scan
    #    uses: SonarSource/sonarcloud-github-action@v2.3.0
    #    env:
    #      SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
    #      args: >
    #        -Dsonar.organization=altheus26 \
    #        -Dsonar.projectKey=altheus26_Laboratorio-final \
      
    #  - name: SonarQube Quality Gate Check   
    #    uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
    #    env:
    #      SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
#----------------------------- SCA ------------------------
    SCA:
      needs: SAST
      runs-on: ubuntu-latest
      steps: 
  
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Clonar Repo
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4.0.2
      
      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16
      - name: Instalar dependencias npm
        run: |
          npm install
      - name: Yarn audit
        run: |
          yarn npm audit 
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: '${{github.event.repository.name}}'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
        
          
      
